image:
  file: .gitpod.Dockerfile

ports:
  # Rails server
  - port: 3000
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore

tasks:
  - init: >
      bundle install &&
      rake db:create &&
      rake db:seed
    command: >
      rails server -b 0.0.0.0

vscode:
  extensions:
    - rebornix.ruby

jetbrains:
  rubymine:
    prebuilds:
      version: both
